import type { Property } from "@saknaha/shared-types";

const interiorImages = [
  "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1560184897-ae75f418493e?auto=format&fit=crop&w=900&q=80",
];

export const mockProperties: Property[] = [
  {
    id: "mock-badee",
    ownerId: "mock-owner",
    ownerName: "أبو خالد",
    ownerPhone: "0551234567",
    title: "شقة هادئة في حي البديع",
    propertyLicenseNumber: "7654321",
    city: "أبها",
    neighborhood: "حي البديع",
    address: "قريبة من الخدمات اليومية",
    universityNearby: "جامعة الملك خالد - قريقر",
    googleMapsUrl: "https://www.google.com/maps?q=18.251,42.502",
    lat: 18.251,
    lng: 42.502,
    classification: "نسائي بالكامل",
    propertyType: "شقة",
    minRooms: 3,
    maxRooms: 3,
    floorsCount: 1,
    hasElevator: false,
    hasCleaningWorker: true,
    hasTransportService: true,
    universityBusPasses: true,
    bathrooms: 2,
    furnished: true,
    maxResidents: 3,
    roommateAllowed: true,
    price: 2000,
    paymentType: "شهري",
    negotiable: true,
    allowWhatsappContact: true,
    deposit: 500,
    priceNotes: "السعر يشمل الصيانة الأساسية.",
    services: [
      {
        id: "s1",
        type: "بقالة",
        name: "بقالة داخل العمارة",
        distanceValue: 1,
        distanceUnit: "walking_minutes",
      },
      {
        id: "s2",
        type: "مواصلات",
        name: "موقف حافلة",
        distanceValue: 3,
        distanceUnit: "walking_minutes",
      },
    ],
    images: [interiorImages[0]],
    status: "published",
    distanceText: "8 دقائق من قريقر",
    timeText: "8 دقائق بالسيارة",
    createdAt: new Date().toISOString(),
  },
  {
    id: "mock-nuzhah",
    ownerId: "mock-owner",
    ownerName: "أبو نورة",
    ownerPhone: "0559876543",
    title: "شقة مفروشة في حي النزهة",
    propertyLicenseNumber: "7654322",
    city: "أبها",
    neighborhood: "حي النزهة",
    address: "قريبة من قريقر وطريق الملك",
    universityNearby: "جامعة الملك خالد - قريقر",
    googleMapsUrl: "https://www.google.com/maps?q=18.239,42.519",
    lat: 18.239,
    lng: 42.519,
    classification: "نسائي بالكامل",
    propertyType: "شقة",
    minRooms: 3,
    maxRooms: 3,
    floorsCount: 1,
    hasElevator: true,
    hasCleaningWorker: true,
    hasTransportService: true,
    universityBusPasses: true,
    bathrooms: 2,
    furnished: true,
    maxResidents: 3,
    roommateAllowed: true,
    price: 2000,
    paymentType: "سنة دراسية",
    negotiable: true,
    allowWhatsappContact: true,
    deposit: 700,
    services: [
      {
        id: "s3",
        type: "مطعم",
        name: "مطعم قريب",
        distanceValue: 5,
        distanceUnit: "walking_minutes",
      },
      {
        id: "s4",
        type: "صيدلية",
        name: "صيدلية الحي",
        distanceValue: 7,
        distanceUnit: "walking_minutes",
      },
    ],
    images: [interiorImages[1]],
    status: "published",
    distanceText: "10 دقائق من قريقر",
    timeText: "10 دقائق بالسيارة",
    createdAt: new Date().toISOString(),
  },
  {
    id: "mock-faraa",
    ownerId: "mock-owner",
    ownerName: "أبو سارة",
    ownerPhone: "0501122334",
    title: "دور نسائي في الفرعاء",
    propertyLicenseNumber: "7654323",
    city: "أبها",
    neighborhood: "الفرعاء",
    address: "دور بنات ودور عوائل في نفس السكن",
    universityNearby: "جامعة الملك خالد - الفرعاء",
    googleMapsUrl: "https://www.google.com/maps?q=18.176,42.62",
    lat: 18.176,
    lng: 42.62,
    classification: "دور نسائي داخل سكن عوائل",
    propertyType: "دور",
    minRooms: 3,
    maxRooms: 3,
    floorsCount: 2,
    hasElevator: false,
    hasCleaningWorker: false,
    hasTransportService: true,
    universityBusPasses: false,
    bathrooms: 2,
    furnished: false,
    maxResidents: 3,
    roommateAllowed: true,
    price: 2000,
    paymentType: "شهري",
    negotiable: false,
    allowWhatsappContact: false,
    services: [
      { id: "s5", type: "جامعة", name: "فرع الفرعاء", distanceValue: 2, distanceUnit: "kilometer" },
      {
        id: "s6",
        type: "مغسلة",
        name: "مغسلة ملابس",
        distanceValue: 6,
        distanceUnit: "walking_minutes",
      },
    ],
    images: [interiorImages[2]],
    status: "published",
    distanceText: "قريب من الفرعاء",
    timeText: "6 دقائق بالسيارة",
    createdAt: new Date().toISOString(),
  },
  {
    id: "mock-king-road",
    ownerId: "mock-owner",
    ownerName: "أبو ريم",
    ownerPhone: "0509988776",
    title: "شقة على طريق الملك",
    propertyLicenseNumber: "7654324",
    city: "أبها",
    neighborhood: "طريق الملك",
    address: "قريبة من فرع طريق الملك",
    universityNearby: "جامعة الملك خالد - طريق الملك",
    googleMapsUrl: "https://www.google.com/maps?q=18.228,42.54",
    lat: 18.228,
    lng: 42.54,
    classification: "متاح للجميع",
    propertyType: "شقة",
    minRooms: 2,
    maxRooms: 3,
    floorsCount: 3,
    hasElevator: true,
    hasCleaningWorker: true,
    hasTransportService: false,
    universityBusPasses: true,
    bathrooms: 1,
    furnished: true,
    maxResidents: 2,
    roommateAllowed: true,
    price: 2000,
    paymentType: "سنوي",
    negotiable: false,
    allowWhatsappContact: true,
    services: [
      {
        id: "s7",
        type: "بقالة",
        name: "سوق صغير",
        distanceValue: 4,
        distanceUnit: "walking_minutes",
      },
      { id: "s8", type: "مطعم", name: "مطعم قريب", distanceValue: 200, distanceUnit: "meter" },
    ],
    images: [interiorImages[3]],
    status: "published",
    distanceText: "قريب من طريق الملك",
    timeText: "5 دقائق بالسيارة",
    createdAt: new Date().toISOString(),
  },
  {
    id: "mock-riyadh-yasmin",
    ownerId: "mock-owner",
    ownerName: "أم نورة",
    ownerPhone: "0554455667",
    title: "شقة قريبة من طريق أنس بن مالك",
    propertyLicenseNumber: "8765101",
    city: "الرياض",
    neighborhood: "حي الياسمين",
    address: "قريبة من الخدمات والمواصلات",
    universityNearby: "قريبة من جامعة الأميرة نورة ومناطق العمل شمال الرياض",
    googleMapsUrl: "https://www.google.com/maps?q=24.829,46.633",
    lat: 24.829,
    lng: 46.633,
    classification: "نسائي بالكامل",
    propertyType: "شقة",
    minRooms: 2,
    maxRooms: 3,
    floorsCount: 4,
    hasElevator: true,
    hasCleaningWorker: true,
    hasTransportService: false,
    universityBusPasses: false,
    bathrooms: 2,
    furnished: true,
    maxResidents: 3,
    roommateAllowed: true,
    price: 2800,
    paymentType: "شهري",
    negotiable: false,
    allowWhatsappContact: true,
    deposit: 1000,
    priceNotes: "السعر لا يشمل الكهرباء.",
    services: [
      {
        id: "riyadh-s1",
        type: "بقالة",
        name: "سوبر ماركت قريب",
        distanceValue: 4,
        distanceUnit: "walking_minutes",
      },
      {
        id: "riyadh-s2",
        type: "مواصلات",
        name: "طريق رئيسي",
        distanceValue: 6,
        distanceUnit: "walking_minutes",
      },
    ],
    images: [interiorImages[0], interiorImages[2]],
    status: "published",
    distanceText: "قريبة من شمال الرياض",
    timeText: "12 دقيقة بالسيارة",
    createdAt: new Date().toISOString(),
  },
  {
    id: "mock-jeddah-salama",
    ownerId: "mock-owner",
    ownerName: "أبو لمى",
    ownerPhone: "0503344556",
    title: "سكن مفروش في حي السلامة",
    propertyLicenseNumber: "8765102",
    city: "جدة",
    neighborhood: "حي السلامة",
    address: "شارع هادئ قريب من الخدمات",
    universityNearby: "قريب من جامعة جدة ومراكز الأعمال",
    googleMapsUrl: "https://www.google.com/maps?q=21.597,39.164",
    lat: 21.597,
    lng: 39.164,
    classification: "نسائي بالكامل",
    propertyType: "سكن مشترك",
    minRooms: 1,
    maxRooms: 2,
    floorsCount: 2,
    hasElevator: false,
    hasCleaningWorker: true,
    hasTransportService: true,
    universityBusPasses: false,
    bathrooms: 1,
    furnished: true,
    maxResidents: 2,
    roommateAllowed: true,
    price: 1900,
    paymentType: "شهري",
    negotiable: false,
    allowWhatsappContact: true,
    services: [
      {
        id: "jeddah-s1",
        type: "مطعم",
        name: "مطاعم قريبة",
        distanceValue: 5,
        distanceUnit: "walking_minutes",
      },
      {
        id: "jeddah-s2",
        type: "صيدلية",
        name: "صيدلية الحي",
        distanceValue: 300,
        distanceUnit: "meter",
      },
    ],
    images: [interiorImages[1], interiorImages[3]],
    status: "published",
    distanceText: "قريبة من الخدمات",
    timeText: "10 دقائق بالسيارة",
    createdAt: new Date().toISOString(),
  },
  {
    id: "mock-dammam-faisaliyah",
    ownerId: "mock-owner",
    ownerName: "أم ريم",
    ownerPhone: "0537788990",
    title: "دور هادئ في الفيصلية",
    propertyLicenseNumber: "8765103",
    city: "الدمام",
    neighborhood: "حي الفيصلية",
    address: "دور مستقل قريب من طريق الملك فهد",
    universityNearby: "قريب من جامعة الإمام عبدالرحمن بن فيصل ومقار العمل",
    googleMapsUrl: "https://www.google.com/maps?q=26.414,50.075",
    lat: 26.414,
    lng: 50.075,
    classification: "متاح للجميع",
    propertyType: "دور",
    minRooms: 3,
    maxRooms: 4,
    floorsCount: 1,
    hasElevator: false,
    hasCleaningWorker: false,
    hasTransportService: false,
    universityBusPasses: false,
    bathrooms: 2,
    furnished: false,
    maxResidents: 4,
    roommateAllowed: false,
    price: 2400,
    paymentType: "شهري",
    negotiable: false,
    allowWhatsappContact: false,
    services: [
      {
        id: "dammam-s1",
        type: "بقالة",
        name: "بقالة قريبة",
        distanceValue: 250,
        distanceUnit: "meter",
      },
      {
        id: "dammam-s2",
        type: "مغسلة",
        name: "مغسلة ملابس",
        distanceValue: 7,
        distanceUnit: "walking_minutes",
      },
    ],
    images: [interiorImages[2]],
    status: "published",
    distanceText: "قريبة من طريق الملك فهد",
    timeText: "15 دقيقة بالسيارة",
    createdAt: new Date().toISOString(),
  },
];
