import type { University, UniversityLocation } from "@saknaha/shared-types";

export const universityCatalog: University[] = [
  { id: "kku", name: "جامعة الملك خالد", region: "منطقة عسير", city: "أبها", active: true },
  {
    id: "ksu",
    name: "جامعة الملك سعود",
    region: "منطقة الرياض",
    city: "الرياض",
    active: true,
  },
  {
    id: "kau",
    name: "جامعة الملك عبدالعزيز",
    region: "منطقة مكة المكرمة",
    city: "جدة",
    active: true,
  },
  {
    id: "iau",
    name: "جامعة الإمام عبدالرحمن بن فيصل",
    region: "المنطقة الشرقية",
    city: "الدمام",
    active: true,
  },
  {
    id: "uqu",
    name: "جامعة أم القرى",
    region: "منطقة مكة المكرمة",
    city: "مكة المكرمة",
    active: true,
  },
  {
    id: "taibah",
    name: "جامعة طيبة",
    region: "منطقة المدينة المنورة",
    city: "المدينة المنورة",
    active: true,
  },
  {
    id: "qu",
    name: "جامعة القصيم",
    region: "منطقة القصيم",
    city: "القصيم",
    active: true,
  },
  {
    id: "tu",
    name: "جامعة تبوك",
    region: "منطقة تبوك",
    city: "تبوك",
    active: true,
  },
];

export const universityBranches: UniversityLocation[] = [
  branch(
    "kku-quraiger",
    "kku",
    "جامعة الملك خالد",
    "أبها",
    "جامعة الملك خالد - قريقر",
    18.2462,
    42.5075,
  ),
  branch(
    "kku-king-road",
    "kku",
    "جامعة الملك خالد",
    "أبها",
    "جامعة الملك خالد - طريق الملك",
    18.2296,
    42.5361,
  ),
  branch(
    "kku-faraa",
    "kku",
    "جامعة الملك خالد",
    "أبها",
    "جامعة الملك خالد - الفرعاء",
    18.1706,
    42.6254,
  ),
  branch(
    "ksu-main",
    "ksu",
    "جامعة الملك سعود",
    "الرياض",
    "جامعة الملك سعود - الحرم الرئيسي",
    24.7225,
    46.6271,
  ),
  branch(
    "kau-main",
    "kau",
    "جامعة الملك عبدالعزيز",
    "جدة",
    "جامعة الملك عبدالعزيز - الحرم الرئيسي",
    21.4931,
    39.2443,
  ),
  branch(
    "iau-main",
    "iau",
    "جامعة الإمام عبدالرحمن بن فيصل",
    "الدمام",
    "جامعة الإمام عبدالرحمن بن فيصل - الحرم الرئيسي",
    26.3927,
    50.1926,
  ),
  branch(
    "uqu-main",
    "uqu",
    "جامعة أم القرى",
    "مكة المكرمة",
    "جامعة أم القرى - العابدية",
    21.3268,
    39.9434,
  ),
  branch(
    "taibah-main",
    "taibah",
    "جامعة طيبة",
    "المدينة المنورة",
    "جامعة طيبة - الحرم الرئيسي",
    24.4816,
    39.5708,
  ),
  branch(
    "qu-main",
    "qu",
    "جامعة القصيم",
    "القصيم",
    "جامعة القصيم - الحرم الرئيسي",
    26.3489,
    43.7668,
  ),
  branch("tu-main", "tu", "جامعة تبوك", "تبوك", "جامعة تبوك - الحرم الرئيسي", 28.3974, 36.4785),
];

function branch(
  id: string,
  universityId: string,
  universityName: string,
  city: string,
  name: string,
  lat: number,
  lng: number,
): UniversityLocation {
  return {
    id,
    universityId,
    universityName,
    city,
    name,
    label: name,
    lat,
    lng,
    active: true,
  };
}
